creation_rules:
  # # Single Encrypted files
  # - path_regex: .*.encrypted
  #   shamir_threshold: 1
  #   key_groups:
  #     - age: 'age1sd0qpf3gc4nlzwpj0y9ff3qdt8z5n4kpp85yg5thdph5yvks9a3snw7tlh'
  # # Encrypted config files
  # - path_regex: .*.yaml
  #   encrypted_regex: ^(data|stringData)$
  #   shamir_threshold: 1
  #   key_groups:
  #     - age: 'age1sd0qpf3gc4nlzwpj0y9ff3qdt8z5n4kpp85yg5thdph5yvks9a3snw7tlh'
  # Catch All
  - age: 'age1sd0qpf3gc4nlzwpj0y9ff3qdt8z5n4kpp85yg5thdph5yvks9a3snw7tlh'
